    <h2 class="hh-legal-notice-chapter"><?= e($chapters['DataProtection']->getHeading()) ?></h2>

    <?php $sectionViews = [
        'Purpose' => 'purpose',
        'PersonalData' => 'personal-data-processing',
        'Privacy' => 'terminology',
        'GDPR' => 'data-categories',
        'ProvidingInformation' => 'data-rights',
    ] ?>

    <?php foreach ($chapters as $chapter) : ?>
        <?php if (!$chapter->getEnabled() || !array_key_exists($chapter->getKey(), $sectionViews)) : ?>
            <?php continue; ?>
        <?php endif ?>

        <?= view($moduleName . '::page/sections/' . $sectionViews[$chapter->getKey()], get_defined_vars()) ?>
    <?php endforeach ?>

