        <h2 class="hh-legal-notice-chapter"><?= e($chapters['LegalRegulations']->getHeading()) ?></h2>
        <?php foreach ($chapters as $chapter): ?>
            <?php if ($chapter->getLink() == $chapters['LegalRegulations']->getId() && $chapter->getEnabled()) : ?>
                <?php $paragraphs = $chapter->getContent() ?>
                <?php if ($paragraphs !== '') : ?>
                    <h3><?= e($chapter->getHeading()) ?></h3>
                    <?php foreach ($paragraphs as $paragraph): ?>
                        <p><?= e($paragraph) ?></p>
                    <?php endforeach ?>
                <?php endif ?>
            <?php endif ?>
        <?php endforeach ?>

