<?php

use Fisharebest\Webtrees\I18N;
?>

    <h3><?= e($chapter->getHeading()) ?></h3>

    <p>
        <?= I18N::plural('I take the protection of the data stored here very seriously.', 'We take the protection of the data stored here very seriously.', $singular ? 1 : 2) ?>

        <?php if ($hostingCountry !== '') : ?>
            <?= I18N::translate('The host for this application is located in %s.', e($hostingCountry)) ?>
        <?php endif ?>

        <?php if ($https) : ?>
            <?= I18N::translate('Transmission to a user browser is encrypted (https).') ?>
        <?php endif ?>

        <?= I18N::translate('The software used (webtrees) offers many protection mechanisms.') ?>
    </p>

    <p>
        <?= I18N::translate('Data assigned to users of this service is processed, as well as data about living and deceased persons.') ?>
    </p>

    <ul>
        <li><?= I18N::translate('Inventory data (names, birth, marriage, and death data, ...)') ?></li>
        <li><?= I18N::translate('Content data (messages, life stories of individuals, photographs, videos, ...)') ?></li>
        <li><?= I18N::translate('Contact data (addresses, e-mail, telephone numbers, ...)') ?></li>
        <li><?= I18N::translate('Usage data (visited web pages, access times, changes made, ...)') ?></li>
        <li><?= I18N::translate('Communication data (device information, browser used, IP addresses, ...)') ?></li>
    </ul>

    <p>
        <?= I18N::translate('To inform you fully about the use of personal data, you are asked to take note of the following privacy information.') ?>
    </p>
