<?php

use Fisharebest\Webtrees\I18N;
?>

    <h3 class="hh-legal-notice-section"><?= e($chapter->getHeading()) ?></h3>

    <p>
        <?= I18N::plural('I take the protection of the data stored here very seriously.', 'We take the protection of the data stored here very seriously.', $singular ? 1 : 2) ?>

        <?php if ($hostingCountry !== '') : ?>
            <?= I18N::translate('The host for this application is located in %s.', e($hostingCountry)) ?>
        <?php endif ?>

        <?= I18N::translate('The software used (webtrees) offers many protection mechanisms.') ?>
    </p>

    <p>
        <?= I18N::translate('A data protection officer has not been appointed because the legal requirements for appointing one are not met.') ?>
    </p>

    <p>
        <?= I18N::translate('To inform you fully about the use of personal data, you are asked to take note of the following privacy information.') ?>
    </p>
