    <h3><?= e($chapter->getHeading()) ?></h3>

    <p>
        Diese Website verarbeitet personenbezogene Daten zum Zwecke der historischen und genealogischen Forschung.
        Sie beschäftigt sich mit der Familien- und Ahnenforschung meiner eigenen Familie,
        der angeheirateten entfernteren Verwandtschaft und der Erforschung von weiteren Personen,
        etwa Trägern meines Familiennamens.
    </p>

    <p>
        Dazu gehören
    </p>
    <ul>
        <li>Zurverfügungstellung des Onlineangebotes, seiner Funktionen und Inhalte</li>
        <li>Beantwortung von Kontaktanfragen und Kommunikation mit den Nutzern</li>
        <li>Sicherheitsmaßnahmen, Reichweitenmessung, Verbesserung des Online-Auftritts</li>
    </ul>
