<?php

use Fisharebest\Webtrees\I18N;
?>

    <h3 class="hh-legal-notice-section"><?= e($chapter->getHeading()) ?></h3>

    <p>
        <?= I18N::translate('This website processes personal data for the purposes of historical and genealogical research.') ?>
    </p>

    <p>
        <?= I18N::translate('This includes:') ?>
    </p>
    <ul>
        <li><?= I18N::translate('Providing the online service, its functions, and its content') ?></li>
        <li><?= I18N::translate('Answering contact requests and communicating with users') ?></li>
        <li><?= I18N::translate('Security measures, reach measurement, and improvement of the online presence') ?></li>
    </ul>

    <?php foreach ($chapters as $subsection) : ?>
        <?php if ($subsection->getLink() !== $chapter->getId() || !$subsection->getEnabled()) : ?>
            <?php continue ?>
        <?php endif ?>

        <h4><?= e($subsection->getHeading()) ?></h4>
        <p><?= $researchPurposeDescriptions[$subsection->getKey()] ?? '' ?></p>
    <?php endforeach ?>
