<?php

use Fisharebest\Webtrees\I18N;
?>

    <h3 class="hh-legal-notice-section"><?= e($chapter->getHeading()) ?></h3>

    <p>
        <?= I18N::translate('This website processes personal data for the purposes of historical and genealogical research.') ?>
        <?= I18N::translate('It deals with family history research into my own family, more distant relatives by marriage, and the research of other persons, such as bearers of my family name.') ?>
    </p>

    <p>
        <?= I18N::translate('This includes:') ?>
    </p>
    <ul>
        <li><?= I18N::translate('Providing the online service, its functions, and its content') ?></li>
        <li><?= I18N::translate('Answering contact requests and communicating with users') ?></li>
        <li><?= I18N::translate('Security measures, reach measurement, and improvement of the online presence') ?></li>
    </ul>
