<?php

use Fisharebest\Webtrees\I18N;
?>

    <h3 class="hh-legal-notice-section"><?= e($chapter->getHeading()) ?></h3>

    <p>
        <?= I18N::translate('Appropriate technical and organizational measures are taken in accordance with legal requirements, taking into account the state of the art, implementation costs, the nature, scope, circumstances, and purposes of processing, and the varying likelihood and severity of the risk to the rights and freedoms of natural persons, in order to ensure a level of security appropriate to the risk.') ?>
    </p>

    <p>
        <?= I18N::translate('These measures include, in particular, securing the confidentiality, integrity, and availability of data, including by controlling access to the data.') ?>
    </p>

    <?php if (count($moduleSecurityMeasures) > 0) : ?>
        <ul>
            <?php foreach ($moduleSecurityMeasures as $moduleSecurityMeasure) : ?>
                <li><?= e($moduleSecurityMeasure) ?></li>
            <?php endforeach ?>
        </ul>
    <?php endif ?>

    <?php if ($https) : ?>
        <h5><?= I18N::translate('SSL or TLS encryption') ?></h5>

        <p>
            <?= I18N::translate('This site uses SSL or TLS encryption to protect the transmission of data.') ?>
            <?= I18N::translate('You can recognize an encrypted connection by the fact that the browser address bar starts with %s, usually also indicated by a lock symbol in your browser bar.', '<code dir="ltr">https://</code>') ?>
            <?= I18N::translate('When SSL or TLS encryption is enabled, the data transmitted cannot be read by third parties.') ?>
        </p>
    <?php endif ?>
