<?php

use Fisharebest\Webtrees\I18N;
?>

    <h3 class="hh-legal-notice-section"><?= e($chapter->getHeading()) ?></h3>

    <p>
        <?= I18N::translate('Appropriate technical and organizational measures are taken in accordance with legal requirements, taking into account the state of the art, implementation costs, the nature, scope, circumstances, and purposes of processing, and the varying likelihood and severity of the risk to the rights and freedoms of natural persons, in order to ensure a level of security appropriate to the risk.') ?>
        <?php if ($https) : ?>
            <?= I18N::translate('Transmission to a user browser is encrypted (https).') ?>
        <?php endif ?>
    </p>

    <p>
        <?= I18N::translate('These measures include, in particular, securing the confidentiality, integrity, and availability of data, including by controlling access to the data.') ?>
    </p>
