<?php

use Fisharebest\Webtrees\I18N;
?>

    <h3 class="hh-legal-notice-section"><?= e($chapter->getHeading()) ?></h3>

    <p>
        <strong><?= I18N::translate('Personal data') ?></strong>
        <?= I18N::translate('means any information relating to an identified or identifiable natural person, hereinafter referred to as the data subject.') ?>
        <?= I18N::translate('An identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier, such as a cookie, or to one or more special characteristics that express the physical, physiological, genetic, mental, economic, cultural, or social identity of that data subject.') ?>
    </p>

    <p>
        <strong><?= I18N::translate('Processing') ?></strong>
        <?= I18N::translate('means any operation performed on personal data, whether or not by automated means.') ?>
        <?= I18N::translate('The term is broad and includes practically any handling of such data.') ?>
    </p>

    <p>
        <strong><?= I18N::translate('Responsible person') ?></strong>
        <?= I18N::translate('means the natural person who, alone or jointly with others, determines the purposes and means of the processing of personal data.') ?>
    </p>
