    <h3><?= e($chapter->getHeading()) ?></h3>

    <p>
        <b>„Personenbezogene Daten“</b> sind alle Informationen,
        die sich auf eine identifizierte oder identifizierbare natürliche Person
        (im Folgenden <b>„betroffene Person“</b>) beziehen;
        als identifizierbar wird eine natürliche Person angesehen, die direkt oder indirekt,
        insbesondere mittels Zuordnung zu einer Kennung wie einem Namen, zu einer Kennnummer, zu Standortdaten,
        zu einer Online-Kennung (z.B. Cookie)
        oder zu einem oder mehreren besonderen Merkmalen identifiziert werden kann,
        die Ausdruck der physischen, physiologischen, genetischen, psychischen, wirtschaftlichen, kulturellen oder
        sozialen Identität dieser betroffenen Person sind.
    </p>

    <p>
        <b>„Verarbeitung“</b> ist jeder mit oder ohne Hilfe automatisierter Verfahren ausgeführte
        Vorgang im Zusammenhang mit personenbezogenen Daten.
        Der Begriff reicht weit und umfasst praktisch jeden Umgang mit diesen Daten.
    </p>

    <p>Als <b>„Verantwortliche Person“</b> wird hier die natürliche Person bezeichnet, die allein oder gemeinsam mit
        anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten entscheidet.
    </p>
